### ISSUE TITLE
fyi

### ISSUE THREAD

**Issue by tkellen** [webdeps/virtual-file#1]
https://github.com/wearefractal/vinyl

**Comment by jonathanong** [comment]
it doesn't do a quarter of the things i need

**Comment by tkellen** [comment]
is it worth like, communicating those needs at all before creating yet another silo?

**Comment by jonathanong** [comment]
not really. they do different things. ex. i'm adding source map support right now. i think that's out of vinyl's scope.

**Comment by tkellen** [comment]
sure, that's outside of vinyl's scope, but there is a fair bit of overlap here. if you need additional functionality why not extend an existing, well-established module that is the basis of an existing, well-established ecosystem? also, the gulp community has a **ton** of knowledge around dealing with sourcemaps in virtual files. it seems like it would be worthwhile to at least *attempt* some knowledge exchange.

/cc @contra @phated

**Comment by jonathanong** [comment]
yeah maybe after i figure out what i'm actually doing. too early right now

**Comment by tkellen** [comment]
roger that. here's hoping a conversation with some people who have been wrestling with these issues for a year or so will be useful. sorry for blowing up your spot, i know open source can be a bit too much of a fishbowl at times.

**Comment by contra** [comment]
if you have a list of what you want i'm always open to adding things
